name: rugged_device_qr_scanner
description: Flutter package for hardware QR/barcode scanning on rugged Android devices. Supports CipherLab industrial scanners.
version: 1.0.0
homepage: https://github.com/webelightsolutions/flutter-rugged-qr-scanner
repository: https://github.com/webelightsolutions/flutter-rugged-qr-scanner
issue_tracker: https://github.com/webelightsolutions/flutter-rugged-qr-scanner/issues
publish_to: https://pub.dev/publishers/webelight.co.in
topics:
  - rugged-device-scanner
  - cipherlab-android-device-scanner
  - barcode-scanner
  - hardware-scanner
  - industrial-scanner

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.rugged_device_qr_scanner
        pluginClass: RuggedScannerPlugin
